import type { DashboardSettings, DashboardSnapshot, DcsServerConfiguration, GrpcInstallationStatus, MissionLibraryResult, MissionReadinessReport } from './types'

export const mockSettings: DashboardSettings = {
  serverName: 'DCS SERVER ONE',
  dcsExecutablePath: 'C:\\Program Files\\Eagle Dynamics\\DCS World Server\\bin-mt\\DCS.exe',
  dcsArguments: '--server --norender',
  savedGamesPath: 'C:\\Users\\dcs-server\\Saved Games\\DCS.server',
  missionLibraryPath: 'D:\\DCS\\Missions',
  tacviewRecordingsPath: 'D:\\DCS\\Tacview',
  activeMissionPath: 'D:\\DCS\\Missions\\Operation Enduring Resolve v4.2.miz',
  maxPlayers: 32,
  integrations: [
    { id: 'grpc', name: 'DCS-gRPC', description: 'Live mission data and server control API', kind: 'managed-service', executablePath: '', arguments: '', configPath: 'C:\\Users\\dcs-server\\Saved Games\\DCS.server\\Config\\dcs-grpc.lua', host: '127.0.0.1', port: 50051, srsAddress: '', telemetryAddress: '' },
    { id: 'srs', name: 'SimpleRadio Standalone', description: 'Voice communications', kind: 'network-process', executablePath: 'C:\\SRS\\SR-Server.exe', arguments: '', configPath: 'C:\\SRS\\server.cfg', host: '127.0.0.1', port: 5002, srsAddress: '', telemetryAddress: '' },
    { id: 'olympus', name: 'DCS Olympus', description: 'Real-time mission control', kind: 'web-process', executablePath: 'C:\\Olympus\\olympus.exe', arguments: '', configPath: 'C:\\Olympus\\olympus.json', host: '127.0.0.1', port: 3000, srsAddress: '', telemetryAddress: '', url: 'http://127.0.0.1:3000' },
    { id: 'tacview', name: 'Tacview', description: 'Flight recording and real-time telemetry', kind: 'telemetry', executablePath: '', arguments: '', configPath: 'C:\\Users\\dcs-server\\Saved Games\\DCS.server\\Config\\options.lua', host: '127.0.0.1', port: 42674, srsAddress: '', telemetryAddress: '' },
    { id: 'skyeye', name: 'SkyEye', description: 'AI-powered GCI', kind: 'process', executablePath: 'C:\\SkyEye\\skyeye.exe', arguments: '', configPath: 'C:\\SkyEye\\config.yaml', host: '127.0.0.1', srsAddress: '127.0.0.1:5002', telemetryAddress: '127.0.0.1:42674' },
    { id: 'dks', name: 'Digital Kneeboard Simulator', description: 'Browser-based mission planning and kneeboards', kind: 'web', executablePath: '', arguments: '', configPath: '', host: '', srsAddress: '', telemetryAddress: '', url: 'https://www.digitalkneeboardsimulator.com/' },
  ],
}

export const mockMissionLibrary: MissionLibraryResult = {
  rootPath: mockSettings.missionLibraryPath,
  configured: true,
  exists: true,
  missions: [
    { name: 'Operation Enduring Resolve v4.2', fullPath: mockSettings.activeMissionPath, relativePath: 'Operation Enduring Resolve v4.2.miz', size: 48_200_000, modified: '2026-07-14T09:42:00Z', active: true },
    { name: 'Flashpoint Levant — Dawn', fullPath: 'D:\\DCS\\Missions\\Flashpoint Levant — Dawn.miz', relativePath: 'Flashpoint Levant — Dawn.miz', size: 36_700_000, modified: '2026-07-12T14:12:00Z', active: false },
    { name: 'Caucasus Training Range', fullPath: 'D:\\DCS\\Missions\\Training\\Caucasus Training Range.miz', relativePath: 'Training\\Caucasus Training Range.miz', size: 12_400_000, modified: '2026-07-08T18:05:00Z', active: false },
  ],
}

export const mockMissionReadiness: MissionReadinessReport = {
  path: mockSettings.activeMissionPath,
  hash: 'e8d66d2e9ab36de9f40dfda6a42614cf86e30b7b5c6f287207ad267cead51c80',
  readable: true,
  status: 'warning',
  title: 'Operation Enduring Resolve v4.2',
  theatre: 'Syria',
  missionDate: '14 Jul 2026',
  startTime: '06:30',
  weather: '27 °C · wind 4 m/s at 275° · scattered clouds',
  size: 48_200_000,
  modified: '2026-07-14T09:42:00Z',
  totalSlots: 36,
  blueSlots: 28,
  redSlots: 8,
  neutralSlots: 0,
  slots: [
    { airframe: 'F-16C_50', coalition: 'Blue', count: 12 },
    { airframe: 'FA-18C_hornet', coalition: 'Blue', count: 8 },
    { airframe: 'AH-64D_BLK_II', coalition: 'Blue', count: 8 },
    { airframe: 'MiG-29A', coalition: 'Red', count: 4 },
    { airframe: 'Mi-24P', coalition: 'Red', count: 4 },
  ],
  dependencies: [
    { name: 'Syria', kind: 'Terrain', status: 'available' },
    { name: 'F-16C', kind: 'Module', status: 'declared' },
    { name: 'AH-64D', kind: 'Module', status: 'declared' },
  ],
  frameworks: ['MOOSE', 'CTLD', 'CSAR', 'Olympus'],
  checks: [
    { severity: 'pass', title: 'Static slots found', detail: '36 Client or Player units were found in the mission data.' },
    { severity: 'warning', title: 'Player cap below slot count', detail: 'The mission exposes 36 static slots while serverSettings.lua allows 32 players.' },
    { severity: 'pass', title: 'Terrain available', detail: 'Syria was found in the configured DCS installation.' },
    { severity: 'info', title: 'Declared modules', detail: 'Additional modules are listed without treating every declaration as a hard client requirement.' },
  ],
}

export const mockServerConfiguration: DcsServerConfiguration = {
  path: `${mockSettings.savedGamesPath}\\Config\\serverSettings.lua`,
  exists: true,
  modified: '2026-07-14T14:12:00Z',
  name: 'Groundcrew Tactical Server',
  description: 'Public training and cooperative missions. SRS is recommended.',
  passwordConfigured: true,
  maxPlayers: 32,
  port: 10308,
  isPublic: true,
  bindAddress: '',
  listLoop: true,
  listShuffle: false,
  resumeMode: 1,
  maxPing: 350,
  requirePureClients: true,
  requirePureScripts: false,
  requirePureTextures: true,
  requirePureModels: true,
  allowOwnshipExport: true,
  allowObjectExport: false,
  allowSensorExport: false,
  allowChangeSkin: true,
  allowChangeTailNumber: true,
  voiceChatServer: false,
  allowTrialOnlyClients: false,
  allowDynamicRadio: true,
  allowPlayersPool: true,
  serverCanScreenshot: false,
}

export const mockGrpcStatus: GrpcInstallationStatus = {
  installed: false,
  running: false,
  loaderConfigured: false,
  autostartConfigured: false,
  canInstall: true,
  installedVersion: null,
  latestVersion: '0.8.1',
  updateAvailable: false,
  host: '127.0.0.1',
  port: 50051,
  savedGamesPath: mockSettings.savedGamesPath,
  missionScriptingPath: 'C:\\Program Files\\Eagle Dynamics\\DCS World Server\\Scripts\\MissionScripting.lua',
  publishedAt: '2024-11-05T18:35:00Z',
  requirementError: null,
}

export const mockSnapshot: DashboardSnapshot = {
  demoMode: true,
  server: {
    state: 'running',
    name: 'DCS SERVER ONE',
    version: '2.9.18.12722',
    mission: 'Operation Enduring Resolve v4.2',
    theatre: 'Syria',
    uptimeSeconds: 17342,
    fps: 58,
    paused: false,
    players: 12,
    maxPlayers: 32,
  },
  metrics: [
    { label: 'CPU', value: 38, unit: '%', max: 100 },
    { label: 'Memory', value: 7.8, unit: 'GB', max: 16 },
    { label: 'DCS process', value: 5.2, unit: 'GB', max: 10 },
    { label: 'Disk', value: 614, unit: 'GB free', max: 1000 },
  ],
  players: [
    { id: '1', name: 'Viper 1-1 | Reaper', side: 'Blue', slot: 'F-16C · Kutaisi', ping: 42, joinedAt: '2026-07-14T12:22:00Z' },
    { id: '2', name: 'Colt 2-1 | Hound', side: 'Blue', slot: 'F/A-18C · CVN-73', ping: 67, joinedAt: '2026-07-14T13:04:00Z' },
    { id: '3', name: 'Enfield 3-2 | Mako', side: 'Red', slot: 'MiG-29A · Bassel Al-Assad', ping: 84, joinedAt: '2026-07-14T13:18:00Z' },
    { id: '4', name: 'Overlord | GCI', side: 'Spectator', slot: 'Game Master', ping: 31, joinedAt: '2026-07-14T11:51:00Z' },
  ],
  integrations: [
    { id: 'grpc', name: 'DCS-gRPC', description: 'Live mission data and server control API', kind: 'managed-service', installed: false, running: false, configurable: true },
    { id: 'srs', name: 'SimpleRadio Standalone', description: 'Voice communications', kind: 'network-process', installed: true, running: true, version: '2.2.0.1', configurable: true },
    { id: 'olympus', name: 'DCS Olympus', description: 'Real-time mission control', kind: 'web-process', installed: true, running: true, version: '2.1.3', url: 'http://127.0.0.1:3000', configurable: true },
    { id: 'tacview', name: 'Tacview', description: 'Flight recording and real-time telemetry', kind: 'telemetry', installed: true, running: false, version: '1.9.4', configurable: true },
    { id: 'skyeye', name: 'SkyEye', description: 'AI-powered GCI', kind: 'process', installed: false, running: false, configurable: true },
    { id: 'dks', name: 'Digital Kneeboard Simulator', description: 'Browser-based mission planning and kneeboards', kind: 'web', installed: true, running: false, url: 'https://www.digitalkneeboardsimulator.com/', configurable: true },
  ],
  chat: [
    { id: 'c1', author: 'SERVER', message: 'Mission loaded: Operation Enduring Resolve v4.2', timestamp: '14:31', system: true },
    { id: 'c2', author: 'Viper 1-1 | Reaper', message: 'Taxiing runway 25, Kutaisi.', timestamp: '14:34' },
    { id: 'c3', author: 'Overlord | GCI', message: 'Picture clean west of the mountains.', timestamp: '14:35' },
  ],
}
